config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'relationships/followings'
  get 'relationships/followers'
  get 'comments/index'
  devise_for :customers
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   resources :animes do
    resources :post, only: [:create, :destroy]
    resources :comments, only: [:index, :show]
    resource :bookmarks, only: [:create, :destroy]
     collection do
      get :bookmarks
    end
   end
   resources :customers, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
     member do
      get :follows, :follows
      get :followers, :followers
       
     end
   end
   get 'home/about' => 'homes#about'

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
  
  Rails.application.routes.draw do
  get 'chats/show'
  namespace :api do
    namespace :v1 do
     resources :animes, only: %i[index]
    end 
  end 
end
  #DM機能
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  # 退会確認画面
  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  # 論理削除用のルーティング
  patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_many :posts,dependent: :destroy
  has_many :bookmarks, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer
  belongs_to :anime
  
  validates :customer_id, uniqueness: { scope: :anime_id}
end

app/models/chat.rb
class Chat < ApplicationRecord
  validates :message, presence: true
  belongs_to :customer
  belongs_to :room
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum subject: { site:0, bug:1, opinion:2, others:3 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  has_many :posts, dependent: :destroy
  #お気に入り機能機能
  has_many :bookmarks, dependent: :destroy

  def bookmark?(anime)
    bookmarks.find_by(anime_id:anime.id).present?
  end

  #フォロー機能
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(customer_id)
    relationships.create(followed_id: customer_id)
  end
  # フォローを外すときの処理
  def unfollow(customer_id)
    relationships.find_by(followed_id: customer_id).destroy
  end
  # フォローしているか判定
  def following?(customer)
    followings.include?(customer)
  end
  
  #DM機能
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  belongs_to :anime
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :customer
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  
  def show
    @customer = Customer.find(params[:id])
    rooms = current_customer.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(customer_id: @customer.id, room_id: rooms)
    
    if user_rooms.nil?
     @room = Room.new
     @room.save
     UserRoom.create(customer_id: @customer.id, room_id: @room.id)
     UserRoom.create(customer_id: current_customer.id, room_id: @room.id)
    else
     @room = user_rooms.room
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_customer.chats.new(params.require(:chat).permit(:message, :room_id))
    @chat.save
  end
  
  private

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
   @anime = Anime.find(params[:anime_id])
   @comments = Post.where(anime_id: @anime.id)
  end
  
  def show
    @customer = Customer.find(params[:id])
    @anime = Anime.find(params[:anime_id])
    @comments = Post.where(anime_id: @anime.id)
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def create
    anime = Anime.find(params[:anime_id])
    comment = current_customer.posts.new(post_params)
    comment.anime_id = anime.id
    comment_count = Post.where(anime_id: params[:anime_id]).where(customer_id: current_customer.id).count
    comment.score = Language.get_data(post_params[:comment])
    #1つのアニメに対して1度しかコメントできないようにする記述
    if comment.valid?
      if comment_count < 1
        comment.save
        redirect_to anime_comments_path(anime.id), notice: "レビューを投稿しました"
      else
        redirect_to anime_comments_path(anime.id), notice: "レビューの投稿は1度までです"
      end
    else
      flash.now[:alert] = "レビューの保存に失敗しました"
      render :new
    end
  end

  def destroy
    Post.find_by(id: params[:id]).destroy
    redirect_to anime_path(params[:anime_id])
  end

  private

  def post_params
    params.require(:post).permit(:comment, :rate)
  end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/curtomers_helper.rb
module CurtomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/comments/index.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="mx-auto pt-3 pb-2"><%= @anime.title %></h1>
  </div>
  <div class='row'>
    <div class="card mt-3 mb-3 mx-auto">
      <div class="card-body login-card-body">
        <div class="d-flex justify-content-around">
          <h4 class="mr-4 text-center">平均点</h4>
          <div id="average-review-rating" class="mx-auto pt-2 pb-2 ml-3" data-score=<%= @comments.average(:rate).to_f.round(1) %>></div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <div>
      <% @comments.each do |post| %>
      <div class="card mt-3 mb-3">
        <div class="card-body login-card-body">
          <div class="mb-3"><%= link_to customer_path(post.customer.id) do %><%= post.customer.name %><% end %></div>
         <div id="review-rating<%= post.id %>" data-score="<%= post.rate %>">評価：</div>
         <span class="sentiment-score">本文の感情分析スコア<%= post.score %></span>
         <p><%= post.comment %></p>
          <% if post.customer == current_customer %>
            <div>
             <%= link_to "削除", anime_post_path(post.anime, post), method: :delete %>
            </div>
          <% end %>
          <script>
          $('#review-rating<%= post.id %>').empty();
          $('#review-rating<%= post.id %>').raty({
            readOnly: true,
            score: function() {
              return $(this).attr('data-score');
            },
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
          });
         </script>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<script>
 $('#average-review-rating').empty();
 $('#average-review-rating').raty({
    size: 36,
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    half: true,
    readOnly: true,
    score: "comment[rate]",
    //注目ポイント↑ 平均点を算出し、round関数で切り上げ
  });
</script>

app/views/comments/show.html.erb
<script>
  function get_animation_title( params ){
    console.log(params);
    $.ajax({
      url: "https://api.annict.com/v1/works"+"?access_token=" + ANNICT_API_KEY + "&filter_ids=" + params,
      type:"GET",
      crossDomain:true,
      dataType : 'json',
      headers:{"accept":"application/json","Access-Control-Allow-Origin":"*"},
    }).done(function (data){
      console.log(data);
      data.works.forEach(anime=>{
        console.log(anime);
        $('.card-title'+anime.id).text(anime.title);
        $('.card-img-top'+anime.id).attr("src",anime.images.facebook.og_image_url);
      });
      // 位置
    }).fail(function (data) {
        //通信失敗
        alert('通信に失敗しました。');
    });
  }
</script>
  <div class="container container-m">
    <div class="row">
     <h1 class="mx-auto pt-4 pb-3">評価したアニメ一覧</h1>
    </div>
      <% @customer.posts.each do |post| %>
        <div class="col-md-10">
          <div class="card mb-4 mt-4 shadow-sm">
            <div class="card-body">
              <%= link_to anime_path(post.anime.anime_id) do %>
                <div class="col d-flex align-items-center border-bottom" style="padding:13px;">
                  <img class="card-img-top<%=post.anime.anime_id%> img-fluid" alt="Card image cap" style="width: 15%;">
                  <p class="mt-3 ml-4 card-title<%=post.anime.anime_id%>"></p>
                </div>
              <% end %>
              <div class="border-bottom" style="padding:13px;" id="review-rating<%= post.id %>" data-score="<%= post.rate %>">評価：</div>
              <span class="sentiment-score">本文の感情分析スコア<%= post.score %></span>
              <ul class="list-group list-group-flush">
              <h5 class="mt-2">
               <font color="#708090">
                 感想
               </font>
              </h5>
             <p class="ml-3"><%= post.comment %></p>
              <% if post.customer == current_customer %>
                <div>
                 <%= link_to "削除", anime_post_path(post.anime, post), method: :delete %>
                </div>
              <% end %>
              <script>
                $('#review-rating<%= post.id %>').empty();
                $('#review-rating<%= post.id %>').raty({
                  readOnly: true,
                  score: function() {
                    return $(this).attr('data-score');
                  },
                  starOn: "<%= asset_path('star-on.png') %>",
                  starOff: "<%= asset_path('star-off.png') %>",
                  starHalf: "<%= asset_path('star-half.png') %>",
                });
              </script>
            </div>
          </div>
        </div>
      <% end %>
      <script>get_animation_title(<%= @customer.posts.joins(:anime).distinct.pluck("animes.anime_id") %>)</script>
    </div>
  </div>
</div>