config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'relationships/followings'
  get 'relationships/followers'
  get 'comments/index'
  devise_for :customers
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   resources :animes do
    resources :post, only: [:create, :destroy]
    resources :comments, only: [:index, :show]
    resource :bookmarks, only: [:create, :destroy]
     collection do
      get :bookmarks
    end
   end
   resources :customers, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
     member do
      get :follows, :follows
      get :followers, :followers
       
     end
   end
   get 'home/about' => 'homes#about'

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
  
  Rails.application.routes.draw do
  get 'chats/show'
  namespace :api do
    namespace :v1 do
     resources :animes, only: %i[index]
    end 
  end 
end
  #DM機能
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  # 退会確認画面
  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  # 論理削除用のルーティング
  patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  has_many :posts, dependent: :destroy
  #お気に入り機能機能
  has_many :bookmarks, dependent: :destroy

  def bookmark?(anime)
    bookmarks.find_by(anime_id:anime.id).present?
  end

  #フォロー機能
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(customer_id)
    relationships.create(followed_id: customer_id)
  end
  # フォローを外すときの処理
  def unfollow(customer_id)
    relationships.find_by(followed_id: customer_id).destroy
  end
  # フォローしているか判定
  def following?(customer)
    followings.include?(customer)
  end
  
  #DM機能
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
class Customers::SessionsController < Devise::SessionsController
  protected

  # 会員の論理削除のための記述。退会後は、同じアカウントでは利用できない。
  def reject_customer
    @customer = Customer.find_by(name: params[:customer][:name])
    if @user
      if @customer.valid_password?(params[:customer][:password]) && (@customer.is_deleted == false)
        flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
        redirect_to new_customer_registration
      else
        flash[:notice] = "項目を入力してください"
      end
    end
  end

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to customer_path(@customer.id)
  end

  def follows
   @customer = Customer.find(params[:id])
   @following_customers = @customer.followings
  end

  def followers
    @customer = Customer.find(params[:id])
    @follower_customers = @customer.followers
  end
  
  def withdrawal
    @customer = Customer.find(params[:id])
    @customer.update(is_deleted: true)
    reset_session
    flash[:notice] = "退会処理を実行しました。"
    redirect_to new_customer_session_path
  end

  private

  def star
    @customer = Customer.find(params[:id])
    @anime = Anime.find(params[:anime_id])
    @comments = Post.where(anime_id: @anime.id)
  end

  def customer_params
    params.require(:customer).permit(:name, :profile_image)
  end

end

app/views/customers/edit.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="mx-auto pt-5 pb-4">マイページ編集</h1>
  </div>
  <div class="col-8 mx-auto mb-4">
    <div class="card ">
      <div class="card-body login-card-body">
      <%= form_with model:@customer, local:true do |f| %>
        <div class="form-group">
         <%= f.label :名前 %>
         <%= f.text_field :name, autofocus: true, class: 'form-control'%>
        </div>
        <div class="form-group">
          <%= f.label :画像 %><br>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
          <%= attachment_image_tag @customer, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
        </div>
        <div>
         <%= f.submit "編集内容を保存する", class: "btn btn-primary save col-xs-6 mb-3" %>
        </div>
      <% end %>
      <%= link_to '退会する', unsubscribe_path, class: "glyphicon glyphicon-tint btn btn-danger"%>
    </div>
  </div>
</div>

app/views/customers/followers.html.erb
 <div class="container">
  <div class="row">
   <h2 class="mx-auto pt-3 pb-1">フォロワー一覧</h2>
  </div>
  
  <% if @follower_customers.exists? %>
   <table class="table">
    <thead>
      <tr>
       <th>image</th>
       <th>name</th>
       <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
     <% @follower_customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.name, customer_path(customer.id) %></td>
        <%#フォロー、フォロワー数をカウントする記述%>
        <td><%= "フォロー #{customer.followings.count}" %></td> 
        <td><%= "フォロワー数: #{customer.followers.count}" %></td>
        <td>
         <% unless current_customer == customer %>
          <% if current_customer.following?(customer) %>
            <%= link_to "フォローを外す", customer_relationships_path(customer.id), method: :delete, class: "btn btn-info" %>
           <% else %>
            <%= link_to "フォロー", customer_relationships_path(customer.id), method: :POST, class: "btn btn-outline-info" %>
           <% end %>
         <% end %>
        </td>
      </tr>
     <% end %>
    </tbody>
  </table>
  <% else %>
   <p>フォローされているユーザーはいません</p>
  <% end %>
 </div>

app/views/customers/followings.html.erb
 <h2>Follow Users</h2>
     <% if @following_customers.exists? %>
     <table class="table">
      <thead>
   　  <tr>
     　 <th>image</th>
     　 <th>name</th>
     　 <th colspan="3"></th>
   　　 </tr>
 　　　 </thead>
     <tbody>
      <% @following_customers.each do |customer| %>
       <tr>
        <td><%= customer.name %></td>
        <td><%= "フォロー数: #{customer.follower.count}" %></td>
        <td><%= "フォロワー数: #{customer.followings.count}" %></td>
        <td>
          <% unless current_customer == customer %>
           <% if current_customer.following?(customer) %>
             <%= link_to "フォローを外す", customer_relationships_path(@customer.id), method: :delete %>
            <% else %>
             <%= link_to "フォロー", customer_relationships_path(@customer.id), method: :POST %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to 'Show', customer_path(@customer.id), class: "user_#{customer.id}" %></td>
       </tr>
      <% end %>
     </tbody>
     </table>
    <% else %>
        <p>ユーザーはいません</p>
    <% end %>

app/views/customers/follows.html.erb
 <div class="container">
  <div class="row">
   <h2 class="mx-auto pt-3 pb-1">フォローしているユーザー一覧</h2>
  </div>
  <% if @following_customers.exists? %>
  <table class="table">
   <thead>
    <tr>
   　 <th>image</th>
   　 <th>name</th>
   　 <th colspan="3"></th>
    </tr>
   </thead>
   <tbody>
    <% @following_customers.each do |customer| %>
     <tr>
      <td><%= link_to customer.name, customer_path(customer.id) %></td>
      <td><%= "フォロー数: #{customer.followings.count}" %></td>
      <td><%= "フォロワー数: #{customer.followers.count}" %></td>
      <td>
        <% unless current_customer == customer %>
         <% if current_customer.following?(customer) %>
           <%= link_to "フォローを外す", customer_relationships_path(customer.id), method: :delete, class: "btn btn-info" %>
          <% else %>
           <%= link_to "フォロー", customer_relationships_path(customer.id), method: :POST, class: "btn btn-outline-info" %>
          <% end %>
        <% end %>
      </td>
     </tr>
    <% end %>
   </tbody>
  </table>
  <% else %>
    <p>フォローしているユーザーはいません</p>
  <% end %>
 </div>

app/views/customers/show.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="mx-auto pt-3 pb-3">ユーザー詳細</h1>
  </div>
  <div class="col-8 mx-auto mb-4">
    <div class="card">
      <div class="card-body login-card-body">
      <table class="table table-bordered table-condensed" >
      <div>
			</div>
      <div class="border-bottom text-right pb-4" style="padding:10px;">
        <% if @customer.id == current_customer.id %>
				 	 <%= link_to edit_customer_path(@customer) do %>
				 	 <h2 class="fas fa-cog text-dark"></h2>
				 	 <% end %>
				<% end %>
				<%= attachment_image_tag @customer, :profile_image, size: "200x200", format: 'jpeg', fallback: "no_image.jpg", class: "rounded-circle d-block mx-auto border" %>
      </div>
        <div class="text-center pt-3 pb-4" font color="#2f4f4f"><h2><%= @customer.name %></h2></div>
					<div class="d-flex justify-content-around">
						<div>
							<h1 class="fas fa-bookmark"></h1><br>
							<h4 class="text-center"><%= link_to "#{@customer.bookmarks.count}", bookmarks_animes_path %></h4>
						</div>
						<div>
							<h1 class="fas fa-user-plus"></h1><br>
							<h4 class="text-center"><%= link_to "#{@customer.followings.count}", follows_customer_path(@customer) %></h4>
						</div>
						<div>
							<h1 class="fas fa-users"></h1><br>
							<h4 class="text-center"><%= link_to "#{@customer.followers.count}", followers_customer_path(@customer) %></h4>
						</div>
						<div>
							<h1 class="fas fa-pen-square"></h1>
							<h4 class="text-center"><%= link_to "#{@customer.posts.count}", anime_comment_path(@customer) %></h4>
						</div>
					</div>
				<% unless current_customer == @customer %>
					<% if current_customer.following?(@customer) %>
					 <div class="pb-4"><%= link_to "フォロー外す", customer_relationships_path(@customer.id), method: :delete, class: "btn btn-info" %></div>
					<% else %>
					 <div class="pb-4"><%= link_to "フォロー", customer_relationships_path(@customer.id), method: :post, class: "btn btn-outline-info" %></div>
					<% end %>
				<% end %>
				<% if current_customer != @customer && current_customer.following?(@customer) && @customer.following?(current_customer) %>
          <%= link_to 'チャットをする', chat_path(@customer.id), class: "btn btn-outline-info"%>
        <% end %>
			</div>
    </div>
  </div>
</div>
</div>

app/views/customers/unsubscribe.html.erb
<h2>退会お手続き</h2>
  <p>
   退会手続きをされますと、全てのサービスがご利用いただけなくなります。<br>
   再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br>
   本当に退会してよろしいですか？
 </p>
 <%= link_to "退会する", withdrawal_path, method: :patch, data: { confilm: "本当に退会しますか？" } %>
 <%= link_to "退会しない", customer_path(current_customer) %>