config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'relationships/followings'
  get 'relationships/followers'
  get 'comments/index'
  devise_for :customers
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   resources :animes do
    resources :post, only: [:create, :destroy]
    resources :comments, only: [:index, :show]
    resource :bookmarks, only: [:create, :destroy]
     collection do
      get :bookmarks
    end
   end
   resources :customers, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
     member do
      get :follows, :follows
      get :followers, :followers
       
     end
   end
   get 'home/about' => 'homes#about'

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
  
  Rails.application.routes.draw do
  get 'chats/show'
  namespace :api do
    namespace :v1 do
     resources :animes, only: %i[index]
    end 
  end 
end
  #DM機能
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  # 退会確認画面
  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  # 論理削除用のルーティング
  patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_many :posts,dependent: :destroy
  has_many :bookmarks, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer
  belongs_to :anime
  
  validates :customer_id, uniqueness: { scope: :anime_id}
end

app/models/chat.rb
class Chat < ApplicationRecord
  validates :message, presence: true
  belongs_to :customer
  belongs_to :room
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum subject: { site:0, bug:1, opinion:2, others:3 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  has_many :posts, dependent: :destroy
  #お気に入り機能機能
  has_many :bookmarks, dependent: :destroy

  def bookmark?(anime)
    bookmarks.find_by(anime_id:anime.id).present?
  end

  #フォロー機能
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(customer_id)
    relationships.create(followed_id: customer_id)
  end
  # フォローを外すときの処理
  def unfollow(customer_id)
    relationships.find_by(followed_id: customer_id).destroy
  end
  # フォローしているか判定
  def following?(customer)
    followings.include?(customer)
  end
  
  #DM機能
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  belongs_to :anime
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :customer
  belongs_to :room
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  def index
    if params[:anime].present?
     if params[:anime].empty?
       @animes = Anime.all
     else
       @animes = Anime.where('title LIKE(?)', "%#{params[:anime][:keyword]}%")
     end
    else
      @animes = Anime.all
    end
  end

  def show
    if Anime.exists?(anime_id: params[:id])
      @animes = Anime.where(anime_id: params[:id])
    else
      @anime = Anime.new(anime_id: params[:id])
      @anime.save
      @animes = Anime.where(anime_id: params[:id])
    end
    @anime = Anime.where(anime_id: params[:id]).last
    @post = Post.new
    @comments = Post.where(anime_id: params[:id]).pluck('comment')
  end

  def new
    @anime = Anime.new
  end

  def create
    anime = Anime.new(anime_params)
    anime.save
    redirect_to animes_path
  end

  def edit
  end

  def search
    respond_to do |format|
      format.html
      format.json
    end
  end

  def bookmarks
    @customer_animes = current_customer.bookmarks&.map(&:anime)
  end

  private
  def anime_params
    params.require(:anime).permit(:title, :image)
  end
end

app/controllers/api/v1/animes_controller.rb
class Api::V1::AnimesController < ApplicationController
  def index
    return if !params[:year] && !params[:season] && !params[:title]
    # paramsによって絞り込みの条件を変更
    
    query = params[:year] && params[:season] ? Work.where(year: params[:year], season: params[:season]) : Anime.where("title like ?", "%#{params[:title]}%")
    animes query.map do |anime|
      {
        id: anime.id,
        title: anime.title,
        year: anime.year,
        season: anime.season
      }
    end
    
    render json: { status:200, animes: animes}
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  
  def show
    @customer = Customer.find(params[:id])
    rooms = current_customer.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(customer_id: @customer.id, room_id: rooms)
    
    if user_rooms.nil?
     @room = Room.new
     @room.save
     UserRoom.create(customer_id: @customer.id, room_id: @room.id)
     UserRoom.create(customer_id: current_customer.id, room_id: @room.id)
    else
     @room = user_rooms.room
    end
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end

  def create
    @chat = current_customer.chats.new(params.require(:chat).permit(:message, :room_id))
    @chat.save
  end
  
  private

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @animes = Anime.joins(:posts).group(:id).order("AVG(posts.rate) desc")
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def create
    anime = Anime.find(params[:anime_id])
    comment = current_customer.posts.new(post_params)
    comment.anime_id = anime.id
    comment_count = Post.where(anime_id: params[:anime_id]).where(customer_id: current_customer.id).count
    comment.score = Language.get_data(post_params[:comment])
    #1つのアニメに対して1度しかコメントできないようにする記述
    if comment.valid?
      if comment_count < 1
        comment.save
        redirect_to anime_comments_path(anime.id), notice: "レビューを投稿しました"
      else
        redirect_to anime_comments_path(anime.id), notice: "レビューの投稿は1度までです"
      end
    else
      flash.now[:alert] = "レビューの保存に失敗しました"
      render :new
    end
  end

  def destroy
    Post.find_by(id: params[:id]).destroy
    redirect_to anime_path(params[:anime_id])
  end

  private

  def post_params
    params.require(:post).permit(:comment, :rate)
  end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/curtomers_helper.rb
module CurtomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/animes/_index.html.erb
<div class="row">
  <div class=" mx-auto">
    <div class="d-flex align-content-start flex-wrap mt-4">
      <div class="container">
      </div>
    </div>
  </div>
</div>

app/views/animes/bookmarks.html.erb
<script>
  function get_animation_title( params ){
    console.log(params);
    $.ajax({
      url: "https://api.annict.com/v1/works"+"?access_token=" + ANNICT_API_KEY + "&filter_ids=" + params,
      type:"GET",
      crossDomain:true,
      dataType : 'json',
      headers:{"accept":"application/json","Access-Control-Allow-Origin":"*"},
    }).done(function (data){
      console.log(data);
      data.works.forEach(anime=>{
        console.log(anime);
        $('.card-title'+anime.id).text(anime.title);
        $('.card-img-top'+anime.id).attr("src",anime.images.facebook.og_image_url);
      });
      
    }).fail(function (data) {
        alert('検索に失敗しました。');
    });
  }
</script>
<div class="container">
  <div class="row">
    <h1 class="mx-auto pt-3 pb-1">ブックマークしたアニメ一覧</h1>
  </div>
  <div class="d-flex align-content-start flex-wrap mt-4">
    <% @customer_animes.each do |bookmark| %>
      <div class="col-md-10">
        <div class="card mb-4 mt-4 shadow-sm">
          <div class="card-body">
            <%= link_to anime_path(bookmark.anime_id) do %>
              <div class="col d-flex align-items-center">
                <img class="card-img-top<%=bookmark.anime_id%> img-fluid" alt="Card image cap" style="width: 15%;">
                <p class="mt-3 ml-4 card-title<%=bookmark.anime_id%>"></p>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<script>get_animation_title(<%= @customer_animes.pluck("anime_id") %>)</script>

app/views/animes/index.html.erb
<div class="container" id="is_anime">
  <div class="row">
    <h1 class="mx-auto pt-3 pb-2">アニメ一覧</h1>
  </div>
  
　<div class="container">
    <%= form_with model: Anime.new, method: :get, class: "search__form" do |f| %>
      <div class="input-group">
        <%= f.text_field :keyword, required: true, class: " search__form__input form-control", id: "form-1", placeholder: 'タイトルを入力して検索' %>
        <span class="input-group-btn">
          <button class="btn btn-primary"  id="btn1" type="submit">
           <i class="fas fa-search"></i>
          </button>
        </span>
      </div>
    <% end %>
    
    <div class="d-flex">
      <%# アニメを検索する為の記述 %>
      <div>
        <%= form_with model: Anime.new, method: :get, class: "mt-3" do |f| %>
         <%= f.select :season, {'2022年春': "2022-spring", '2022年夏': "2022-summer", '2022年秋': "2022-autumn", '2022年冬': "2022-winter",'2021年春': "2021-spring", '2021年夏': "2021-summer", '2021年秋': "2021-autumn", '2021年冬': "2021-winter", '2020年春': "2020-spring", '2020年夏': "2020-summer", '2020年秋': "2020-autumn", '2020年冬': "2020-winter", '2019年春': "2019-spring", '2019年夏': "2019-summer", '2019年秋': "2019-autumn", '2019年冬': "2019-winter",}, include_blank: "放送時期で検索", class: "form-control" %>
         <button class="btn btn-primary"  id="btn2" type="submit">検索する</button>
        <% end %>
      </div>
    </div>
    
    <div class='col-6 mx-auto mb-4'>
      <div id="index">
       <%= render "animes/index", animes: @animes %>
      </div>
    </div>
    
  </div>
</div>
<div class="container container-m">
<div class="card-deck" id="title">

app/views/animes/index.js.erb
$("#index").html("<%= escape_javascript(render partial: "animes/index", locals: {animes: @animes}) %>");

app/views/animes/new.html.erb
<h1>新規投稿</h1>
<%= form_with model:@anime, local:true do |f| %>

<h4>タイトル</h4>
<%= f.text_field :title %>

<h4>アニメ画像</h4>
<%= f.attachment_field :image, placeholder:"アニメ画像" %>

<%= f.submit '投稿' %>

<% end %>

app/views/animes/show.html.erb
<ul id="title"></ul>
<div class="container">
  <div>
    <p>コメント件数: <%= @anime.posts.count %></p>
  </div>
  <div>
    <p><%= link_to "コメント一覧", anime_comments_path(@anime.id) %></p>
  </div>
  <div class="mb-2">
    <% if customer_signed_in? %>
      <%= render 'bookmarks/bookmark_area', anime: @anime %>
    <% else %>
     <div></div>
    <% end %>
　</div>
　<%# アニメの評価と感想を送信する記述 %>
  <%= form_with(model:[@anime,@post], url: anime_post_index_path(@anime.id), local: true) do |f| %>
    <div class="form-group">
     <%= f.text_area :comment, rows:'5',placeholder: "感想をここに", class: 'form-control mb-3' %>
      <% if customer_signed_in? %>
        <div id="evaluate_stars">
         <%= f.submit "送信する", class: 'mb-3' %>
        </div>
      <% else %>
        評価を送信するにはログインしてください
      <% end %>
    </div>
  <% end %>
  <%#APIからデータをとってくるための記述 %>
<script>
  $(function(){
     const val = $(".search__form__input").val();
      var params = { filter_ids: <%= @anime.anime_id %> };
      api_call( params);
      });
      function api_call( params ){
    console.log(params);
    $.ajax({
      url: "https://api.annict.com/v1/works"+"?access_token=" + ANNICT_API_KEY,
      type:"GET",
      crossDomain:true,
      dataType : 'json',
      headers:{"accept":"application/json","Access-Control-Allow-Origin":"*"},
      data: params,

    }).done(function (data){
      console.log(data);
      data.works.forEach(anime=>{
        console.log(anime);
        $('<div class="container pt-5"><div class="row"><div class="col-8 mx-auto"><div class="card u-card-flat"><div class="card-body mx-auto"><img class=" card-img-top'+anime.id+' img-fluid " src="..." alt="Card image cap"><div class="card-body"><p class="card-title'+anime.id+'">Card title</p><p class="card-text"></p></div></div>').appendTo("#title");
        $('.card-title'+anime.id).text(anime.title);
        $('.card-img-top'+anime.id).attr("src",anime.images.facebook.og_image_url);
      });
    }).fail(function (data) {
      alert('検索に失敗しました。');
    });
}
  $('#evaluate_stars').raty({
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    scoreName: 'post[rate]'
  });
</script>