config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'relationships/followings'
  get 'relationships/followers'
  get 'comments/index'
  devise_for :customers
  root to: 'homes#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   resources :animes do
    resources :post, only: [:create, :destroy]
    resources :comments, only: [:index, :show]
    resource :bookmarks, only: [:create, :destroy]
     collection do
      get :bookmarks
    end
   end
   resources :customers, only: [:show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
     member do
      get :follows, :follows
      get :followers, :followers
       
     end
   end
   get 'home/about' => 'homes#about'

  resources :contacts, only: [:new, :create]
  post 'contacts/confirm', to: 'contacts#confirm', as: 'confirm'
  post 'contacts/back', to: 'contacts#back', as: 'back'
  get 'done', to: 'contacts#done', as: 'done'
  
  Rails.application.routes.draw do
  get 'chats/show'
  namespace :api do
    namespace :v1 do
     resources :animes, only: %i[index]
    end 
  end 
end
  #DM機能
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  
  # 退会確認画面
  get '/customers/:id/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  # 論理削除用のルーティング
  patch '/customers/:id/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
end

app/models/anime.rb
class Anime < ApplicationRecord
  has_many :posts,dependent: :destroy
  has_many :bookmarks, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :customer
  belongs_to :anime
  
  validates :customer_id, uniqueness: { scope: :anime_id}
end

app/models/chat.rb
class Chat < ApplicationRecord
  validates :message, presence: true
  belongs_to :customer
  belongs_to :room
end

app/models/contact.rb
class Contact < ApplicationRecord
  enum subject: { site:0, bug:1, opinion:2, others:3 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  has_many :posts, dependent: :destroy
  #お気に入り機能機能
  has_many :bookmarks, dependent: :destroy

  def bookmark?(anime)
    bookmarks.find_by(anime_id:anime.id).present?
  end

  #フォロー機能
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理
  def follow(customer_id)
    relationships.create(followed_id: customer_id)
  end
  # フォローを外すときの処理
  def unfollow(customer_id)
    relationships.find_by(followed_id: customer_id).destroy
  end
  # フォローしているか判定
  def following?(customer)
    followings.include?(customer)
  end
  
  #DM機能
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
  
  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :customer
  belongs_to :anime
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :customer
  belongs_to :room
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def create
    anime = Anime.find(params[:anime_id])
    comment = current_customer.posts.new(post_params)
    comment.anime_id = anime.id
    comment_count = Post.where(anime_id: params[:anime_id]).where(customer_id: current_customer.id).count
    comment.score = Language.get_data(post_params[:comment])
    #1つのアニメに対して1度しかコメントできないようにする記述
    if comment.valid?
      if comment_count < 1
        comment.save
        redirect_to anime_comments_path(anime.id), notice: "レビューを投稿しました"
      else
        redirect_to anime_comments_path(anime.id), notice: "レビューの投稿は1度までです"
      end
    else
      flash.now[:alert] = "レビューの保存に失敗しました"
      render :new
    end
  end

  def destroy
    Post.find_by(id: params[:id]).destroy
    redirect_to anime_path(params[:anime_id])
  end

  private

  def post_params
    params.require(:post).permit(:comment, :rate)
  end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/curtomers_helper.rb
module CurtomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/_footer.html.erb
<div id="footer" class="fixed-bottom" style="background-color:#808080;">
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>© 2022 Tomii Jin</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
 <div id="header" class="sticky-top" style="background-color:#f5f5f5;">
  <nav class="navbar navbar-expand-lg navbar-dark border" style="padding:10px;">
   <div class="container">
    <a class="navbar-brand">
     <h1 class="mt-3 mb-3 text-dark"><%= link_to(root_path) do %><%= image_tag 'icon4-removebg-preview.png' %><% end %></h1>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
       <p class="text-right">
        <% if customer_signed_in? %>
         <li></li>
         <h5><%= link_to 'アニメ一覧', animes_path, class: "btn btn-outline-info text-dark mx-3 d-flex align-items-center"  %></h5>
         <h5><%= link_to 'マイページ', customer_path(current_customer.id), class: "btn btn-outline-info text-dark mx-3 pr-3 d-flex align-items-center" %></h5>
         <h5><%= link_to 'アバウト', home_about_path, class: "btn btn-outline-info text-dark mx-3 pr-3 d-flex align-items-center" %></h5>
         <h5><%= link_to 'お問い合わせ', new_contact_path, class: "btn btn-outline-info text-dark mx-3 pr-3 d-flex align-items-center" %></h5>
         <h5><%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class: "btn btn-outline-info text-dark mx-3 pr-3 d-flex align-items-center" %></h5>
        <% else %>
         <li></li>
         <h5><%= link_to 'アニメ一覧', animes_path, class: "btn btn-outline-info text-dark mx-3 d-flex align-items-center" %></h5>
         <h5><%= link_to 'アバウト', home_about_path, class: "btn btn-outline-info text-dark mx-3 pr-4 d-flex align-items-center" %></h5>
         <h5><%= link_to '新規登録', new_customer_registration_path, class: "btn btn-outline-info text-dark mx-3 pr-4 d-flex align-items-center" %></h5>
         <h5><%= link_to 'ログイン', new_customer_session_path, class: "btn btn-outline-info text-dark mx-3 pr-4 d-flex align-items-center" %></h5>
        <% end %>
       </p>
      </ul>
     </div>
    </div>
   </div>
  </nav>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Anieva</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="Content/bootstrap.css" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render 'layouts/header' %>

  <body style="background-color:#f0f8ff;">
    <div class="container">
      <div class="text-center">
       <%= flash[:notice] %>
      </div>
      <%= yield %>
    </div>
  </body>
  
  <div class="mt-5">
    <%= render 'layouts/footer' %>
  </div>
</html>